# Generated by Django 5.2.5 on 2025-08-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('track', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='trainee/images')),
            ],
        ),
    ]
