# Generated by Django 5.2.5 on 2025-08-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainee_trackid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
