# Generated by Django 5.2.5 on 2025-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='first_track_name',
            field=models.CharField(default='track name', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='second_track_name',
            field=models.CharField(default='second track name', max_length=60),
            preserve_default=False,
        ),
    ]
