# Generated by Django 5.2.5 on 2025-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_first_track_name_track_second_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='first_track_image',
            field=models.ImageField(default='first track name', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='second_track_image',
            field=models.ImageField(default='second track name', upload_to=''),
            preserve_default=False,
        ),
    ]
