# Generated by Django 5.2.5 on 2025-08-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_track_first_track_image_track_second_track_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='first_track_image',
            field=models.ImageField(upload_to='track1/images/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='second_track_image',
            field=models.ImageField(upload_to='track2/images/'),
        ),
    ]
