# Generated by Django 5.2.5 on 2025-08-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_track_first_track_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
